apiVersion: apps/v1 
kind: Deployment
metadata:
  name: petclinic-sample-0
  labels:
    app: petclinic-app-0
spec:
  replicas: 1
  selector:
   matchLabels:
     app: petclinic-deployment
  template:
    metadata:
      labels:
        name: petclinic-deployment
        app: petclinic-deployment
        app.kubernetes.io/name: "myapp"
        version: v1
    spec:
      volumes:
      - name: test-volume
      containers:
      - name: petclinic-tomcat
        image: kruize/spring_petclinic:2.2.0-jdk-11.0.8-openj9-0.21.0
        imagePullPolicy: Always
        resources:
         requests:
         limits:
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: "test-volume"
            mountPath: "/opt/jLogs"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-0
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/manage/prometheus'
  labels:
    app: petclinic-app-0
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 32334
      targetPort: 8081
      name: petclinic-port-0
  selector:
    name: petclinic-deployment

