apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic
  labels:
    team: petclinic-frontend
spec:
  selector:
    matchLabels:
        app: petclinic-app
  endpoints:
    - port: petclinic-port
      path: '/manage/prometheus'
