apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-sample
  labels:
    app: acmeair-app
spec:
  replicas: 1
  selector:
   matchLabels:
     app: acmeair-deployment
  template:
    metadata:
      labels:
        name: acmeair-deployment
        app: acmeair-deployment
        # Add label to the application which is used by kruize/autotune to monitor it
        app.kubernetes.io/name: "acmeair-deployment"
        version: v1
    spec:
      volumes:
      - name: test-volume
        hostPath:
          path: "/root/icp/jLogs"
          type: ""
      containers:
      - name: acmeair-libertyapp
        image: quay.io/kruizehub/acmeair-monolithic
        imagePullPolicy: IfNotPresent
        env:
        - name: "MONGO_HOST"
          value: "acmeair-db"
        ports:
          - containerPort: 8080
        resources:
         requests:
         limits:
        volumeMounts:
          - name: "test-volume"
            mountPath: "/opt/jLogs"
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-service
  labels:
    app: acmeair-app
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32221
      targetPort: 8080
      name: http
  selector:
    name: acmeair-deployment
