apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-sample-1
  labels:
    app: acmeair-app-1
spec:
  replicas: 1
  selector:
   matchLabels:
     app: acmeair-deployment
  template:
    metadata:
      labels:
        name: acmeair-deployment
        app: acmeair-deployment
        app.kubernetes.io/name: "myapp"
        version: v1
    spec:
      volumes:
      - name: test-volume
        hostPath:
          path: "/root/icp/jLogs"
          type: ""
      containers:
      - name: acmeair-libertyapp
        image: dinogun/acmeair-monolithic
        imagePullPolicy: Always
        env:
        - name: "JVM_ARGS"
          value: "-Xshareclasses:none -Xverbosegclog:/opt/jLogs/verbosegc.xml"
        - name: "MONGO_HOST"
          value: "acmeair-db"
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: 500M
            cpu: 0.5
        volumeMounts:
          - name: "test-volume"
            mountPath: "/opt/jLogs"
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-service-1
  labels:
    app: acmeair-app-1
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32222
      targetPort: 8080
      name: http
  selector:
    name: acmeair-deployment
