apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-db
  labels:
    app: acmeair-db
spec:
  replicas: 1
  selector:
   matchLabels:
     app: acmeair-db
  template:
    metadata:
      labels:
        name: acmeair-db
        app: acmeair-db
        # Add label to the application which is used by kruize/autotune to monitor it
        app.kubernetes.io/name: "acmeair-db"
        version: v1
    spec:
      containers:
      - name: acmeair-db
        image: quay.io/kruizehub/mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-db
  labels:
    name: acmeair-db
spec:
    type: ClusterIP
    selector:
      app: acmeair-db
    ports:
      - protocol: TCP
        port: 27017
        targetPort: 27017
