apiVersion: apps/v1
kind: Deployment
metadata:
  name: renaissance-sample
  labels:
    app: renaissance-app
spec:
  replicas: 1
  selector:
   matchLabels:
     app: renaissance-deployment
  template:
    metadata:
      labels:
        name: renaissance-deployment
        app: renaissance-deployment
        # Add label to the application which is used by kruize/autotune to monitor it
        app.kubernetes.io/name: "renaissance-deployment"
        app.kubernetes.io/layer: "hotspot"
        version: v1
    spec:
      volumes:
      - name: test-volume
      containers:
      - name: renaissance-server
        image: prakalp23/renaissance1041:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: "JDK_JAVA_OPTIONS"
            value: " "
          - name: "BENCHMARK"
            value: "all"
          - name: "TIME_LIMIT"
            value: "5"
        ports:
          - containerPort: 8080
        resources:
         requests:
         limits:
        volumeMounts:
          - name: "test-volume"
            mountPath: "/opt/jLogs"
---
apiVersion: v1
kind: Service
metadata:
  name: renaissance-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    app: renaissance-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: renaissance-port
  selector:
    name: renaissance-deployment
